import type { Metadata } from "next";
import { Inter, Notable } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";

// Import Google Notable font
const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const notable = Notable({ subsets: ['latin'], weight: '400', variable: '--font-notable' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${notable.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
